export const WELCOME_SCREEN = 'WELCOME_SCREEN';
export const REGISTRATION_SCREEN = 'REGISTRATION_SCREEN';
export const PROFILE_SELECTION_SCREEN = 'PROFILE_SELECTION_SCREEN';
export const CONTACTS_SCREEN = 'CONTACTS_SCREEN';
export const CONTACT_SCREEN = 'CONTACT_SCREEN';
export const BLACKLIST_SCREEN = 'BLACKLIST_SCREEN';
export const PROFILE_SCREEN = 'PROFILE_SCREEN';
export const CHANGE_ANON_PROFILE_SCREEN = 'CHANGE_ANON_PROFILE_SCREEN';
export const TAB_NAVIGATOR = 'TAB_NAVIGATOR';
export const LOADING_SCREEN = 'LOADING_SCREEN';
export const APP_LOADING_SCREEN = 'APP_LOADING_SCREEN';

export const CHAT_LIST_SCREEN = 'CHATS_LIST_SCREEN';
export const ACTIVE_CHAT_SCREEN = 'ACTIVE_CHAT_SCREEN';
export const IMAGE_FULL_SCREEN = 'IMAGE_FULL_SCREEN';

export const AUTHENTICATION_STACK = 'AUTHENTICATION_STACK';
